### ISSUE TITLE
ModuleNotFoundError: No module named 'onelogin.api'; 'onelogin' is not a package

### ISSUE THREAD

**Issue by pythoninthegrass** [onelogin/onelogin-python-sdk#52]
## Environment
debian buster 10.10 (docker), macOS 10.14.6, onelogin 1.9.1, python 3.9.5, pipenv 2020.11.15, pip 21.1.1

## Issue
Can't import with `ModuleNotFoundError` raised. Easiest way to reproduce is by `pip install onelogin`, then running `python -c 'from onelogin.api.client import OneLoginClient'`:
```bash
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/mnt/onelogin.py", line 14, in <module>
    from onelogin.api.client import OneLoginClient
ModuleNotFoundError: No module named 'onelogin.api'; 'onelogin' is not a package
```
## Longform Repro
* `pipenv`
    ```bash
    pipenv install onelogin python-decouple
    pipenv run pip list
    pipenv run python onelogin_edit.py
    pipenv --rm
    ```

* `virtualenv`
    ```bash
    python3 -m venv env
    source env/bin/activate
    pip3 install -r requirements.txt
    python onelogin_edit.py
    ```

* `docker`
    ```bash
    # Setup
    docker pull python:3.9.5-buster
    docker tag 'python:3.9.5-buster' python

    # Run clean container and mount local code
    docker run -v $(pwd):/mnt -w '/mnt' --name python --rm -it python bash
    cat /etc/os-release

    # Dependencies
    pip3 install -r requirements.txt
    python --version

    # Standalone import
    python -c 'from onelogin.api.client import OneLoginClient'

    # Script
    python onelogin_edit.py
    ```

## Edited Script
```python
import os
from decouple import AutoConfig
from onelogin.api.client import OneLoginClient

# env
home = os.path.expandvars("$HOME")
env = os.getcwd() + '/.env'

# creds
config = AutoConfig(os.getcwd())
if os.path.exists(env):
    client_id = config('client_id')
    client_secret = config('client_secret')
else:
    client_id = os.getenv('client_id')
    client_secret = os.getenv('client_secret')

# Init client
client = OneLoginClient(
    client_id,
    client_secret
)

# Get an AccessToken
token = client.get_access_token()

# All users
client.get_users()
```

**Comment by pitbulk** [comment]
Is onelogin listed at requirements.txt in your environment? was it successfully installed in your system?

I executed with no issues:
```
python3 -m venv env
source env/bin/activate
pip3 install onelogin python-decouple
python onelogin_edit.py
```

**Comment by pythoninthegrass** [comment]
Yes, `onelogin` is listed in the requirements. Same results in both `pipenv` and vanilla `virtualenv`.
`requirements.txt`
```
#
# These requirements were autogenerated by pipenv
# To regenerate from the project's Pipfile, run:
#
#    pipenv lock --requirements
#

-i https://pypi.org/simple
certifi==2021.5.30
chardet==4.0.0; python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2, 3.3, 3.4'
defusedxml==0.7.1; python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2, 3.3, 3.4'
idna==2.10; python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2, 3.3'
onelogin==1.9.1
python-dateutil==2.8.1; python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2'
python-decouple==3.4
requests==2.25.1
six==1.16.0; python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2'
urllib3==1.26.6; python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2, 3.3, 3.4' and python_version < '4'
```
`virtualenv`
```
$ pip list
Package         Version
--------------- ---------
certifi         2021.5.30
chardet         4.0.0
defusedxml      0.7.1
idna            2.10
onelogin        1.9.1
pip             21.1.2
python-dateutil 2.8.1
python-decouple 3.4
requests        2.25.1
setuptools      57.0.0
six             1.16.0
urllib3         1.26.6
wheel           0.36.2
```
`onelogin_edit.py`
```
$ python onelogin_edit.py
Traceback (most recent call last):
  File "/Users/lance.stephens/git/Rx/onelogin/onelogin_edit.py", line 3, in <module>
    from onelogin.api.client import OneLoginClient
  File "/Users/lance.stephens/git/Rx/onelogin/onelogin.py", line 14, in <module>
    from onelogin.api.client import OneLoginClient
ModuleNotFoundError: No module named 'onelogin.api'; 'onelogin' is not a package
```

**Comment by pythoninthegrass** [comment]
Closing the loop. @elenaelago jogged my memory about how it's a mistake to name scripts the same thing as imported libraries. Been long enough I don't remember if I was only testing the original `onelogin.py` and posting the snippet here `¯\_(ツ)_/¯`

Thanks for taking a look @pitbulk
