### ISSUE TITLE
Exception when creating a role

### ISSUE THREAD

**Issue by webratz** [onelogin/onelogin-python-sdk#76]
When trying to create a new role, there is an exception raised within the library.
Its not clear what could be the issue / what could be done to avoid this, so I assume a problem within th lib

Trace
```txt
Traceback (most recent call last):
  File "/Users/foobar/git/onelogin/create-roles.py", line 65, in <module>
    api_response = api_instance.create_roles(role)
  File "/Users/foobar/.local/share/virtualenvs/onelogin-apW85H0z/lib/python3.10/site-packages/onelogin/api/default_api.py", line 8213, in create_roles
    return self.create_roles_endpoint.call_with_http_info(**kwargs)
  File "/Users/foobar/.local/share/virtualenvs/onelogin-apW85H0z/lib/python3.10/site-packages/onelogin/api_client.py", line 880, in call_with_http_info
    return self.api_client.call_api(
  File "/Users/foobar/.local/share/virtualenvs/onelogin-apW85H0z/lib/python3.10/site-packages/onelogin/api_client.py", line 422, in call_api
    return self.__call_api(resource_path, method,
  File "/Users/foobar/.local/share/virtualenvs/onelogin-apW85H0z/lib/python3.10/site-packages/onelogin/api_client.py", line 227, in __call_api
    return_data = self.deserialize(
  File "/Users/foobar/.local/share/virtualenvs/onelogin-apW85H0z/lib/python3.10/site-packages/onelogin/api_client.py", line 333, in deserialize
    deserialized_data = validate_and_convert_types(
  File "/Users/foobar/.local/share/virtualenvs/onelogin-apW85H0z/lib/python3.10/site-packages/onelogin/model_utils.py", line 1583, in validate_and_convert_types
    converted_instance = attempt_convert_item(
  File "/Users/foobar/.local/share/virtualenvs/onelogin-apW85H0z/lib/python3.10/site-packages/onelogin/model_utils.py", line 1458, in attempt_convert_item
    raise get_type_error(input_value, path_to_item, valid_classes,
onelogin.exceptions.ApiTypeError: Invalid type for variable 'received_data'. Required value type is list and passed type was dict at ['received_data']
```

Version: 3.1.0
Simplified sample code:
```python
configuration = onelogin.Configuration(
    host = "https://api.us.onelogin.com"
)


configuration = onelogin.Configuration(
    access_token = bearer_token
)


with onelogin.ApiClient(configuration) as api_client:
    # Create an instance of the API class
    api_instance = default_api.DefaultApi(api_client)
    role = Role(name="name_example") # Role | 

    try:
        api_response = api_instance.create_roles(role)
        pprint(api_response)
    except onelogin.ApiException as e:
        print("Exception when calling DefaultApi->create_roles: %s\n" % e)
´´´

**Comment by Jmfwolf** [comment]
Can you please try the updated one?
https://github.com/onelogin/onelogin-python-sdk/releases/tag/3.1.1

There were several issues in the previous specification that have sense been corrected

**Comment by webratz** [comment]
This seems not to be released on pypi and direct install fails
```txt
pip install git+https://github.com/onelogin/onelogin-python-sdk.git@3.1.1#egg=onelogin
ollecting onelogin
  Cloning https://github.com/onelogin/onelogin-python-sdk.git (to revision 3.1.1) to /private/var/folders/xs/y4klp7z93515p95l119grphw0000gq/T/pip-install-j3xm55b8/onelogin_4569488171fc4fa6a4ebafa619f7b9d4
  Running command git clone --filter=blob:none --quiet https://github.com/onelogin/onelogin-python-sdk.git /private/var/folders/xs/y4klp7z93515p95l119grphw0000gq/T/pip-install-j3xm55b8/onelogin_4569488171fc4fa6a4ebafa619f7b9d4
  Running command git checkout -q 8a292744c495556ac0ed231fac1df6e695c61d02
  Resolved https://github.com/onelogin/onelogin-python-sdk.git to commit 8a292744c495556ac0ed231fac1df6e695c61d02
  Preparing metadata (setup.py) ... done
  WARNING: Generating metadata for package onelogin produced metadata for project name openapi-client. Fix your #egg=onelogin fragments.
Discarding git+https://github.com/onelogin/onelogin-python-sdk.git@3.1.1#egg=onelogin: Requested openapi-client from git+https://github.com/onelogin/onelogin-python-sdk.git@3.1.1#egg=onelogin has inconsistent name: expected 'onelogin', but metadata has 'openapi-client'
ERROR: Could not find a version that satisfies the requirement onelogin (unavailable) (from versions: 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.3.2, 1.4.0, 1.4.1, 1.4.2, 1.4.3, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.6.0, 1.6.1, 1.7.0, 1.8.0, 1.8.1, 1.8.2, 1.9.0, 1.9.1, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 3.0.0a1, 3.0.0b1, 3.0.0, 3.0.1, 3.1.0)
ERROR: No matching distribution found for onelogin (unavailable)
```

**Comment by webratz** [comment]
The problem seems to be the wrong name in https://github.com/onelogin/onelogin-python-sdk/blob/3.1.1/setup.py#L21

**Comment by Jmfwolf** [comment]
Try using `sudo python3 setup.py install --user`
I was able to use the SDK installing that method.
The pip install method I haven't gotten to work and may need to remove from the readme
